name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Find JAR File
        run: |
          echo "Searching for JAR file..."
          JAR_FILE=$(find $GITHUB_WORKSPACE/target -name '*.jar')
          echo "Found JAR file: $JAR_FILE"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        run: |
          echo "Copying JAR file to EC2 server..."
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          rsync -zvhr -e "ssh -i private_key.pem" $JAR_FILE ubuntu@43.204.114.46:/home/ubuntu/pro/prashant-demo/target/

          echo "Deploying on EC2 server..."
          ssh -i private_key.pem ubuntu@43.204.114.46 "bash -s" << EOF
            # Execute any additional deployment steps here
            java -jar /home/ubuntu/pro/prashant-demo/target/$(basename $JAR_FILE)
          EOF


