name: United-Platform-Dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Find JAR File
        run: |
          echo "Searching for JAR file..."
          find $GITHUB_WORKSPACE/target -name '*.jar'

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Copy JAR to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            scp -i "$HOME/.ssh/id_rsa" $GITHUB_WORKSPACE/prashant-demo/target/springboot-example.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/pro/prashant-demo/target/
            
