name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "target/your-artifact-id-*.jar"
          target: "/home/ubuntu/pro/prashant-demo/target/"

      - name: SSH into EC2 and restart application
        uses: appleboy/ssh-action@v0.5.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /path/to/destination/folder/
            # Assuming your application is running as a service
            sudo service nginx restart

