name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Find JAR File
        run: |
          echo "Searching for JAR file..."
          JAR_FILE=$(find $GITHUB_WORKSPACE/target -name '*.jar')
          echo "Found JAR file: $JAR_FILE"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Copying JAR file to EC2 server..."
            rsync -zvhr -e "ssh -i <(echo '${{ secrets.EC2_PRIVATE_KEY }}')" $JAR_FILE ubuntu@43.204.114.46:/home/ubuntu/live-shopping-dev-stag/live-shopping-authentication-node-service/build/

            echo "Deploying on EC2 server..."
            ssh -i <(echo '${{ secrets.EC2_PRIVATE_KEY }}') ubuntu@43.204.114.46 "bash -s" << EOF
              # Execute any additional deployment steps here
              java -jar /home/ubuntu/live-shopping-dev-stag/live-shopping-authentication-node-service/build/$(basename $JAR_FILE)
            EOF
