name: Java CI/CD with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: prashant-runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package 


